# Generated by Django 2.0.4 on 2018-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180508_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'surname')},
        ),
    ]
