# Generated by Django 2.0.4 on 2018-05-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='user',
        ),
    ]
